import React, { useEffect } from 'react';
import './custom_home.css'; // Import page-specific CSS directly

const Home = () => {
    useEffect(() => {
        // Dynamically set the document title
        document.title = 'Welcome to the World of Electromagnetics';
    }, []);

    return (
        <div className="home-container">
            <section className="greeting-section">
                <h1>Welcome to the World of Electromagnetics</h1>
                <p>
                    Electromagnetic Field (EM) Theory is one of the fundamental courses for both Electrical and Electronics Engineering disciplines. 
                    Generally, students perceive it as a difficult course to understand and they feel that the course is abstract and too mathematical. 
                    It is essential to explain the involved theory in the course through real-life practical examples and visual aids.
                </p>
                <p>
                    In this virtual EM laboratory, the concepts of vector calculus and underlying theories in electrostatics, magnetostatics, and 
                    time-varying electromagnetic fields are explained using field plots generated by formulae and Finite Element Method (FEM) based computations.
                </p>
                <p>
                    This web-based laboratory has been developed by using Java Applets and Java Scripts, which provide interactive features such as 
                    radio buttons and provision for drawing contours. The theory and examples given should be used as complementary material to a 
                    standard textbook on electromagnetics like the one mentioned below [A].
                </p>
            </section>

            <section className="experiments-section">
                <h2>About the Experiments</h2>
                <p>
                    The serial number of the experiments is given as per the chapter numbers of [A] in which the corresponding theory appears.
                </p>
                <p>
                    <strong>[A]</strong> M.N.O. Sadiku and S.V. Kulkarni, Principles of Electromagnetics, Sixth Edition, Oxford University Press, India, 2015 
                    (Asian adaptation of 'M.N.O. Sadiku, Elements of Electromagnetics, Sixth International Edition, Oxford University Press').
                </p>
            </section>
        </div>
    );
};

export default Home;
